name: My First CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from my first CI/CD pipeline!"

      - name: Build Docker image
        run: docker build -t my-webpage -f my-webpage/Dockerfile my-webpage/

      - name: Verify image was built
        run: docker images
